---
title: "GroceryList: Basic Javascript"
type: "challenge"  # challenge, exercise, article, video
description: "Lesson Description."
tags: "javascript, systems-check"
ignore:
- "grocery-list-basic-javascript.md"
